### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format

### ISSUE THREAD

**Issue by chris-aeviator** [retroplasma/earth-reverse-engineering#1]
When using your example octants (or others) I will get the following error thrown:

arch linux
```
node --version
v10.10.0
```

```
[…]
found: 20527061605273514374
found: 20527061605273514375
found: 20527061605273514376
found: 20527061605273514377
octants: 149
(node:3681) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:3681) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
(node:3681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I can see the files beeing created into `downloaded_files`, they have a size but will not open correctly (tried to import with blender & open with g3dviewer)

**Comment by chris-aeviator** [comment]
Turns out that I can get the export running with node.

```
❯ node --version                      
v9.11.2
```

Do you happen to know why the produced files are incompatible to be opened with blender? I tried with blender 2.79 & 2.8beta, they will only show up in the object list but won't have any representation in the 3d view? I can open them though in an arbitrary obj online viewer..

**Comment by vdwijngaert** [comment]
> Turns out that I can get the export running with node.
> 
> ```
> ❯ node --version                      
> v9.11.2
> ```

Even with node 9.11.2 I get those errors. Did you try anything else?

**Comment by chris-aeviator** [comment]
> Even with node 9.11.2 I get those errors. Did you try anything else?

When researching the `Input file is missing or of an unsupported image format` error I came across a hint with an incompatible build of `libvips`, which I had not even installed, so I installed only that and after switching to node 9.11.2 it was working.

**Comment by chris-aeviator** [comment]
> This should do the trick: ![select_object](https://user-images.githubusercontent.com/46618410/51100320-6878ea00-17cd-11e9-82f8-fbf6deff5609.jpg)

What an obvious solution - thanks :smile:

**Comment by bicubic** [comment]
v9.11.2 same issue with sample input parameters. 

```
(node:25512) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
(node:25512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vdwijngaert** [comment]
> v9.11.2 same issue with sample input parameters.
> 
> ```
> (node:25512) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
> (node:25512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:25512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
> In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Installing libvips [like chris-aeviator said](https://github.com/retroplasma/earth-reverse-engineering/issues/1#issuecomment-453923931) worked for me!

**Comment by bicubic** [comment]
> Installing libvips [like chris-aeviator said](https://github.com/retroplasma/earth-reverse-engineering/issues/1#issuecomment-453923931) worked for me!

Did not help me.

**Comment by dmos62** [comment]
I'm experiencing the same exception when sharp tries to convert the ppm file to a jpg. In my case, it's a bug in sharp, since converting a jpg to ppm with irfanview (I'm on windows) and trying to convert it back with sharp produces same error.

**Comment by leoherzog** [comment]
Same here, Ubuntu 18.04, Node v10.15.0.

```
(node:26378) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:26378) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
(node:26378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by unrealwill** [comment]
I encountered the problem and installing libvips didn't solve the issue.

For the octant I was downloading it downloaded ppm files so I "hard-coded" it. and manually disabled the file conversion to png and suppression of ppm.

I edited L112
`map_Kd ${texName}.ppm`
 
I commented L141 and L142
```
 //await sharp(`${dir}/${texName}.ppm`).toFile(`${dir}/${texName}.png`);
//execSync(`rm ${dir}/${texName}.ppm`);
```
Then it works, I can open it in meshlab

**Comment by skadge** [comment]
Thanks @unrealwill, this solved the same problem for me too (ubuntu 18.04, node 8.11.4)

**Comment by retroplasma** [comment]
@unrealwill good idea, i'll provide an option for this. PPM doesn't work for me in Blender though.

Could you try with node 8.15.0? Works on macOS. It installed libvips 8.7.0.

**Comment by skadge** [comment]
@retroplasma FYI I loaded material in Blender by first converting everything back to PNGs (`mogrify -format png *.ppm`) (and replacing accordingly the extensions in the mlt file)

**Comment by retroplasma** [comment]
I removed `sharp` for simplicity's sake. The code produces jpg and bmp (via `bmp-js`) now. no more ppm. Also added a bash script for converting bmp/jpg to png (optional)
