### ISSUE TITLE
We should avoid object shift and scale "hack"

### ISSUE THREAD

**Issue by LexSong** [retroplasma/earth-reverse-engineering#10]
The coordinates have their physical meanings. The origin is earth center and the length unit is meter.

Maybe it's better to keep the original coordinates, or add an option to let the user choose how to normalize the output mesh.

**Comment by bicubic** [comment]
Yes please. Or emit normalized mesh and offset+scale vectors.

**Comment by retroplasma** [comment]
makes sense, I decoupled it. scaling/moving can be done manually using `scale_move_obj.sh` now
