### ISSUE TITLE
What software to view the files (with textures)?

### ISSUE THREAD

**Issue by deerhunter91** [retroplasma/earth-reverse-engineering#14]
What applications on Linux/Mac OSX can be used to view the files with textures? I tried FXB Review and Photoshop and neither show textures. Thanks

**Comment by CihanSari** [comment]
I have used MeshLab with quite a bit of success.

**Comment by retroplasma** [comment]
Blender, Xcode

**Comment by deerhunter91** [comment]
Thanks everyone for the suggestions.
