### ISSUE TITLE
[Error] Get TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by LexSong** [retroplasma/earth-reverse-engineering#17]
I just update to the latest version and get this error:

    > node index.js 205172436353455 17

    found: 205172436353455
    found: 2051724363534550
    found: 20517243635345503
    TypeError: Cannot read property 'length' of null
        at search (C:\Users\LexSong\earth-reverse-engineering\index.js:133:28)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)

I tried to `git bisect`, and found that the commit 2197458 caused the error.

**Comment by retroplasma** [comment]
Thank you! Fixed
