### ISSUE TITLE
Some octants are kind of wrong

### ISSUE THREAD

**Issue by Rakiah** [retroplasma/earth-reverse-engineering#19]
Hello, latest master broke the cross-platform compatibility (it was working yesterday) here are the logs:

```
node.exe lat_long_to_octant.js 48.856086, 2.297932
48.856086, 2.297932
-------------
30 { n: 90, s: 0, w: 0, e: 90 }
306 { n: 90, s: 45, w: 0, e: 90 }
3060 { n: 67.5, s: 45, w: 0, e: 45 }
30604 { n: 56.25, s: 45, w: 0, e: 22.5 }
306040 { n: 50.625, s: 45, w: 0, e: 11.25 }
3060406 { n: 50.625, s: 47.8125, w: 0, e: 5.625 }
30604060 { n: 49.21875, s: 47.8125, w: 0, e: 2.8125 }
306040607 { n: 49.21875, s: 48.515625, w: 1.40625, e: 2.8125 }
3060406071 { n: 48.8671875, s: 48.515625, w: 2.109375, e: 2.8125 }
30604060716 { n: 48.8671875, s: 48.69140625, w: 2.109375, e: 2.4609375 }
306040607163 { n: 48.8671875, s: 48.779296875, w: 2.28515625, e: 2.4609375 }
3060406071636 { n: 48.8671875, s: 48.8232421875, w: 2.28515625, e: 2.373046875 }
30604060716362 { n: 48.8671875,
  s: 48.84521484375,
  w: 2.28515625,
  e: 2.3291015625 }
306040607163624 { n: 48.856201171875,
  s: 48.84521484375,
  w: 2.28515625,
  e: 2.30712890625 }
3060406071636243 { n: 48.856201171875,
  s: 48.8507080078125,
  w: 2.296142578125,
  e: 2.30712890625 }
30604060716362436 { n: 48.856201171875,
  s: 48.85345458984375,
  w: 2.296142578125,
  e: 2.3016357421875 }
306040607163624362 { n: 48.856201171875,
  s: 48.854827880859375,
  w: 2.296142578125,
  e: 2.29888916015625 }
3060406071636243627 { n: 48.856201171875,
  s: 48.85551452636719,
  w: 2.297515869140625,
  e: 2.29888916015625 }
30604060716362436276 { n: 48.856201171875,
  s: 48.855857849121094,
  w: 2.297515869140625,
  e: 2.2982025146484375 }
306040607163624366 { n: 48.856201171875,
  s: 48.854827880859375,
  w: 2.296142578125,
  e: 2.29888916015625 }
3060406071636243663 { n: 48.856201171875,
  s: 48.85551452636719,
  w: 2.297515869140625,
  e: 2.29888916015625 }

node dump_obj.js 3060406071636243663 20
TypeError: Cannot read property '0' of null
    at Fd.T.Ja (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:13:111839)
    at Fd.T.Fa (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:13:109954)
    at rf.a (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:13:114798)
    at Object.c.onmessage (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:13:114410)
    at C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:29:9
    at new Promise (<anonymous>)
    at decode (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\decode-resource.js:27:16)
    at decode (C:\Users\rakia\gitlab\tools\earth-reverse-engineering\lib\utils.js:73:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
octants: 0
```

**Comment by Rakiah** [comment]
actually going from:
`node dump_obj.js 3060406071636243663 20`
to
`node dump_obj.js 306040607163624366 20` worked, so I think this may be unrelated, shall I close ?

**Comment by retroplasma** [comment]
Dunno about `TypeError: Cannot read property '0' of null`. But I don't think it's a windows issue. Might be something with the data.

`node dump_obj.js 306040607163624366 20` got me some bushes.

`node dump_obj.js 30604060716362436 20` got me this:
<img width="817" alt="img" src="https://user-images.githubusercontent.com/46618410/51440973-8f02bd80-1cc4-11e9-9030-d4e9e9ab5e1f.png">

looks like the place at 48.856086, 2.297932
<img width="673" alt="img" src="https://user-images.githubusercontent.com/46618410/51441011-18b28b00-1cc5-11e9-9587-aaf0e7f08e9a.png">

**Comment by Rakiah** [comment]
this may be linked to the lat_long_to_octant.js script actually aswell ?

**Comment by LexSong** [comment]
@Rakiah

The `lat_long_to_octant.js` script actually traverse the octant tree depth-firstly.

In your example, 306040607163624362 is the octant with the same level,and just below 306040607163624366.

![snapshot02](https://user-images.githubusercontent.com/35987111/51491844-9fad5380-1dea-11e9-95ef-4620f4d274df.png)
![snapshot01](https://user-images.githubusercontent.com/35987111/51491848-a3d97100-1dea-11e9-9d70-18349b66adf1.png)

You should get both octants to get the best result, if you want to dump objs at finer scale instead of dump larger area.

There is still a lot of things needed to do to smooth the whole process.

**Comment by Rakiah** [comment]
Thanks for the explanation, may you explain me what's the difference between zoom level and depth ? Because we can specify the zoom level in the dump_obj.js call, if it's the same as depth why is it needed ?

**Comment by retroplasma** [comment]
@Rakiah It's the same, i just called it zoom level up there. It's the depth of the octree in which all model data is stored. The higher the number the more details we get. It's specified to limit the level of detail.

<img width="230" alt="img" src="https://user-images.githubusercontent.com/46618410/51552442-8814b000-1e68-11e9-8937-3a6b63adf87e.png"><img width="239" alt="img" src="https://user-images.githubusercontent.com/46618410/51552459-91058180-1e68-11e9-8dcc-03571ec195af.png">

**Comment by TysonGersh** [comment]
> @Rakiah
> 
> The `lat_long_to_octant.js` script actually traverse the octant tree depth-firstly.
> 
> In your example, 306040607163624362 is the octant with the same level, and just below 306040607163624366.
> 
> ![snapshot02](https://user-images.githubusercontent.com/35987111/51491844-9fad5380-1dea-11e9-95ef-4620f4d274df.png)
> ![snapshot01](https://user-images.githubusercontent.com/35987111/51491848-a3d97100-1dea-11e9-9d70-18349b66adf1.png)
> 
> You should get both octants to get the best result, if you want to dump objs at finer scale instead of dump larger area.
> 
> There is still a lot of things needed to do to smooth the whole process.

Okay, so just to confirm that I understand (or that I don't) what you're saying..... 
Basically each octant has different objects of the overall scene/model? So we need to run each octant in order to get a scene/model that features the entire environment? 

In other words, that bush from the octant that only imports a bush wouldn't be present in the octant that appears to have everything in it? You have to do both octants if you want the information both of them reference?

**Comment by LexSong** [comment]
Yes, at certain depth/zoom level, there will be octants on different
heights. They cover the same north-south and east-west range but not on the
same height.

The lat-long-to-octant script will try to find all of them and output from
the lowest to highest.

TysonGersh <notifications@github.com> 於 2019年1月24日 週四 上午4:22寫道：

**Comment by TysonGersh** [comment]
> Yes, at certain depth/zoom level, there will be octants on different heights. They cover the same north-south and east-west range but not on the same height. The `lat-long-to-octant` script will try to find all of them and output from the lowest to highest.

Is there anyway to download all the needed octants at one? Having to download download them one at a time seems really time-consuming. Like, can we just put a comma in between the octants and still run Dump_obj ####, #####, #####, ####, 18 ( or 20... still not entirely sure what's going on w the last number part)

**Comment by retroplasma** [comment]
@TysonGersh it handles multiple octants now:
```
node dump_obj.js octant_1 octant_2 ... octant_n max_level
```

**Comment by TysonGersh** [comment]
> @TysonGersh it handles multiple octants now:
> 
> ```
> node dump_obj.js octant_1 octant_2 ... octant_n max_level
> ```

so.... any idea what I'm doing wrong here? 
<img width="786" alt="screen shot 2019-01-23 at 6 49 44 pm" src="https://user-images.githubusercontent.com/46682958/51644858-bf09c500-1f3f-11e9-8218-4d791e014f31.png">

**Comment by retroplasma** [comment]
@TysonGersh pull updated code from github

**Comment by TysonGersh** [comment]
@retroplasma uhhhhhhh?
<img width="811" alt="screen shot 2019-01-23 at 7 31 22 pm" src="https://user-images.githubusercontent.com/46682958/51646193-908ee880-1f45-11e9-9479-fede5d4b6b03.png">

**Comment by retroplasma** [comment]
@TysonGersh First level here (21) represents a top slice of the earth. Next one represents a smaller region "around" your coordinates, and so forth. The latlong script gives you North/South/West/East boundaries so you see how big the area is for each level.

The dump script starts at one level and tries to dump everything up to your specified "max level". You give it the first octant(s) at one start level and it goes down from there until it reaches that max.

Which level and max-level to choose depends on the area and level-of-detail that you want your full model to cover.

~visualization: https://github.com/retroplasma/earth-reverse-engineering/issues/19#issuecomment-456481828

> Please forgive me for not understanding completely

No problem. It means that it's not intuitive yet. Thanks for the feedback :)
