### ISSUE TITLE
Can't load BulkMetadata at 1s204162437140

### ISSUE THREAD

**Issue by LexSong** [retroplasma/earth-reverse-engineering#23]
C:\Users\LexSong\earth-reverse-engineering>node dump_obj.js 204162437140 12
    found: 204162437140
    octants: 1

    C:\Users\LexSong\earth-reverse-engineering>node dump_obj.js 204162437140 13
    found: 204162437140
    Error: HTTP status code 404 for https://kh.google.com/rt/earth/BulkMetadata/pb=!1m2!1s204162437140!2u823

Not sure about why there is a 404.

**Comment by retroplasma** [comment]
There's no bulk at that index; only a node. Should be fixed now. Nice find!
