### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by levelsio** [retroplasma/earth-reverse-engineering#3]
(node:56060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by caglorithm** [comment]
macOS 10.14.2, node over homebrew, same error

**Comment by leoherzog** [comment]
Same here, Ubuntu 18.04.

```
(node:26378) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:26378) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
(node:26378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by noqnio** [comment]
Changing all `new Buffer` to `new Buffer.from` gets rid of the warning, leaving only
```
(node:4768) UnhandledPromiseRejectionWarning: Error: Input file is missing or of
 an unsupported image format
(node:4768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:4768) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```
resulting in a 120KB obj file using the suggested octant, unable to be displayed in Blender.
Could you please share your node and npm versions so we can run it with a similar environment to yours?
Thanks

**Comment by calebegg** [comment]
For the record, that's a warning, not an error. Output from this script goes to ./downloaded_files, and it's working fine for me despite the warnings.

**Comment by TysonGersh** [comment]
> For the record, that's a warning, not an error. Output from this script goes to ./downloaded_files, and it's working fine for me despite the warnings.

I'm getting: (node:50025) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 
but not seeing anything in downloads. I'm newer to this. Am I looking in the wrong place?

**Comment by retroplasma** [comment]
@leoherzog @levelsio Can you try node 8?

**Comment by levelsio** [comment]
> For the record, that's a warning, not an error. Output from this script goes to ./downloaded_files, and it's working fine for me despite the warnings.

Not sure, maybe unrelated, but after this warning pops up, half the textures are missing from the model when I view it in an OBJ viewer.

**Comment by leoherzog** [comment]
@retroplasma Can confirm, expected output and no warnings on Node 8.

**Comment by retroplasma** [comment]
ok, i close is then. node 8 is in the readme

**Comment by desmondCTNG** [comment]
Instead of forcing people to use Node 8, you can simply replace two lines in decode-texture.js to solve the problem:

1) `return { extension: 'jpg' , buffer: new Buffer(tex.bytes) };`     => `return { extension: 'jpg' , buffer: Buffer.from(tex.bytes) };`

2) `const buf = new Buffer(bytes);`   => `const buf = Buffer.from(bytes);`
