### ISSUE TITLE
Error: EEXIST from mkdir when attempting to run dump_obj.js

### ISSUE THREAD

**Issue by e-murray** [retroplasma/earth-reverse-engineering#33]
I have used this a number of times with no problems but suddenly I am getting an "EEXIST" error when attempting to run dump_obj.js. I have confirmed the file is definitely not in the folder so I am unsure why I am getting this error.

![mkdir EEXIST error](https://user-images.githubusercontent.com/52741387/62852984-ee68ff00-bce2-11e9-97f7-803f2e17e15e.png)

**Comment by disembarkedone** [comment]
looks like a new version of fs-extra

the issue appears to be that it's trying to create a directory that already exists and fails

try removing the output directory

**Comment by e-murray** [comment]
Thanks for the reply, I thought that too but I have used fs-extra 7.0.1 before with no problems. I double checked the output directory in question "downloaded_files" is not there before running dump_obj.js but it still throws the error. 

I wonder if it could be due to npm install creating the node_modules directory which dump_obj.js then attempts to create itself, causing confict? I tried a global install of fs-extra to try and sidestep the issue but it resulted in a "Cannot find module  'fs extra' " error.

**Comment by retroplasma** [comment]
@e-murray does it work if you specify less octants?

**Comment by e-murray** [comment]
@retroplasma I think you are right as I then ran it on Ubuntu and got the ENAMETOOLONG error, which was solved by using a lower octant level as you say. Thanks.

**Comment by Darkressxx** [comment]
This issue is cause because the path that the script is trying to create is just too long.
Removing the `${OCTANTS.join('+')` parameter at `dump_obj.js:28` would fix it!

**Comment by chris-aeviator** [comment]
> This issue is caused because the path that the script is trying to create is just too long.
Removing the ${OCTANTS.join('+') parameter at dump_obj.js:28 would fix it!

I think this is an essential fix since why should I work with low res files when I can have high res zoom 16 data?

**Comment by retroplasma** [comment]
@chris-aeviator pushed

**Comment by chris-aeviator** [comment]
@retroplasma great & thanks ! :+1:
