### ISSUE TITLE
Is this information still relevant?

### ISSUE THREAD

**Issue by lewa-j** [retroplasma/earth-reverse-engineering#34]
I tried to decode the mesh using the information from Readme.md, as well as dump_obj.js, but nothing worked. It seems to me that during this time, the layout of the mesh vertices has changed.
I've tried node https://kh.google.com/rt/earth/NodeData/pb=!1m2!1s214272516372616353!2u852!2e1!4b0
There are 3 mesh in this file. Each of them contains 18744, 3678 and 1809 bytes of vertices. Second and third not even a multiple of 8.

**Comment by retroplasma** [comment]
it is still working:

`node dump_obj.js 214272516372616353 20`
![image](https://user-images.githubusercontent.com/46618410/64133517-e9c1d300-cdd6-11e9-8d9c-53b80edf8b41.png)

one level up:

`node dump_obj.js 21427251637261635 20`
![image](https://user-images.githubusercontent.com/46618410/64133529-f8a88580-cdd6-11e9-84e3-279f55768a6c.png)

**Comment by lewa-j** [comment]
I am trying to do the same in C#. Maybe proto files in the repository are not the same as those used in js?

**Comment by retroplasma** [comment]
The proto in this repo is incomplete; [here](https://github.com/retroplasma/earth-reverse-engineering/issues/31) is one with more detail which only lacks NodeData field 8. The vertices byte array straight from the proto (field 1) is a multiple of 3; it only contains XYZ. A vertex buffer is created with a count divisible by 8 from XYZ, UV (field 7) and layer/octant-counts (field 8).

XYZ processing works ~ like this:
```JS
var count = vertices.length / 3;
var output = new Uint8Array(8 * count);
for (var i = 0, axis = 0; axis < 3; axis++) {       
  for (var j = 0, d = 0; j < count; j++) {
    d = (d + input[i++]) & 0xFF;
    output[8 * j + axis] = d;
  }
}
```

Unfortunately I didn't have time yet to make this stuff transparent.

**Comment by lewa-j** [comment]
Many thanks! This is exactly what I was missing. From README.md it seemed that XYZWUUVV was exactly the format of the vertices field.
