### ISSUE TITLE
Models are messed up

### ISSUE THREAD

**Issue by olejka2k** [retroplasma/earth-reverse-engineering#39]
Hi
Thanks for your research on this great tool!
Though, I have a problem using it. For some reason, my model is coming up totally messed. I am importing OBJ into 3dsmax, after centering-scaling script, and it looks like this: [https://dl.dropboxusercontent.com/s/xb8r3gh32b6m9ko/shot_190909_165318.png](url)
Can you please let me know what the issue can be?
Thanks a lot!

**Comment by retroplasma** [comment]
Which octant(s) and level did you use? Have you tried Blender as well?

**Comment by olejka2k** [comment]
> Which octant(s) and level did you use? Have you tried Blender as well?

I tried your settings without any changes - for a clean test. Did not try blender though, let me try it and I will come back.

**Comment by olejka2k** [comment]
Everything is fine in Blender! I exported from Blender to 3dsMax and it is ok as well. 3dsmax at it's best - always messes up even simple things...
