### ISSUE TITLE
[QUESTION] Difference between octants returned by PR #25 and the ones used by `dump_obj.js`

### ISSUE THREAD

**Issue by ndepal** [retroplasma/earth-reverse-engineering#42]
I just stumbled across this project and I'm very intrigued by it. But I'm struggling to understand how the octants work. In particular, I'm using @LexSong's script `find_overlaps.py` (https://github.com/retroplasma/earth-reverse-engineering/issues/25) to find which octants I need for a given area described by Lat/Lon corners.

That script gives me several octants for various levels. However, when I pass these octants to `dump_obj.js`, it sometimes is not able to download any data. Why is this?

Even more confusing, sometimes it only fails for some of the octants of a given level returned by `find_overlaps.py` but others of the same level work.

In the tests that I have done so far, the octants that did work actually covered the bounding box I asked for and I did not seem to be missing data, even though some octants `find_overlaps.py` listed for that level did not download anything. Is it safe to assume that for any level, the subset of the octants listed by `find_overlaps.py` that successfully download will actually cover the bounding box of interest?

Lastly, a question regarding the parameters passed to `dump_obj.js`: What does the second number passed do exactly? Is it not the same as the octant level? If so, why do we need to specify it again, is it not already defined by the octant we also pass to `dump_obj.js`?

Thanks any help you can provide!

**Comment by retroplasma** [comment]
I'm not 100% sure about `find_overlaps.py` and its completion; it seems like it doesn't check if an octant actually has data. So it should return more octants. The downloader would skip those.

The other number parameter of `dump_obj.js` is the maximum level. So let's say you pass it 1234567890123456 20 then will search until 1234567890123456XXXX.

**Comment by ndepal** [comment]
Thanks for the clarification!
