### ISSUE TITLE
[MISC] Vertex to Voxel etc. (2/2)

### ISSUE THREAD

**Issue by TheJavaProfessor** [retroplasma/earth-reverse-engineering#44]
O yeah, i also changed some files.
On the link you can find some adapted .sh .bat .js files.
For the octants i adapted it to find ranges from 2 lat/lon cords. so you end up with all the needed octants. I've read something about it on the issues here.
For west i adapted the source a little, so it also works on minus lon cords. I could not fix it quickly in one file. For doing the same trick on the southern part you need to do the same for the lons.
Then i also changed it to create c++ files, for loading the calculated octants into (this case c/c++) program. So you can list them like x,y coords., and get the right octant dir.
You can look it up. I give you a few links and start uploading the latest changes.

Your program adapted files for usage...
https://github.com/TheJavaProfessor/MINECRAFT-WORLD-CREATOR/tree/master/EARTH

The created c++ source with https://github.com/TheJavaProfessor/MINECRAFT-WORLD-CREATOR/blob/master/EARTH/lat_long_to_octant_min_lon.js
->
https://github.com/TheJavaProfessor/MINECRAFT-WORLD-CREATOR/blob/master/PACMAN_CUBERITE/src/include/test_data.hpp

Sample:
std::string get_octant_NewYork(int &x, int &y) {
    static std::string *octants[80];
    static int first_do=1;
    if (x<0 || y<0) {
        x=80;y=58;
        if (first_do==0) return "";
    }
    if  (first_do==1) {
        first_do=0;
        x=42;y=130;
        octants[0]=new std::string[130] {"21427251635371524","21427251635371435","21427251635371434","21427251635371425","21427251635371424","21427251635370535","21427251635370534","21427251635370525","21427251635370524","21427251635370435","21427251635370434","21427251635370425","21427251635370424","21427251635361535","21427251635361534","21427251635361525","21427251635361524","21427251635361435","21427251635361434","21427251635361425","21427251635361424","21427251635360535","21427251635360534","21427251635360525","21427251635360524","21427251635360435","21427251635360434","21427251635360425","21427251635360424","21427251635271535","21427251635271534","21427251635271525","21427251635271524","21427251635271435","21427251635271434","21427251635271425","21427251635271424","21427251635270535","21427251635270534","21427251635270525","21427251635270524","21427251635270435","21427251635270434","21427251635270425","21427251635270424","21427251635261535","21427251635261534","21427251635261525","21427251635261524","21427251635261435","21427251635261434","21427251635261425","21427251635261424","21427251635260535","21427251635260534","21427251635260525","21427251635260524","21427251635260435","21427251635260434","21427251635260425","21427251635260424","21427251634371535","21427251634371534","21427251634371525","21427251634371524","21427251634371435","21427251634371434","21427251634371425","21427251634371424","21427251634370535","21427251634370534","21427251634370525","21427251634370524","21427251634370435","21427251634370434","21427251634370425","21427251634370424","21427251634361535","21427251634361534","21427251634361525","21427251634361524","21427251634361435","21427251634361434","21427251634361425","21427251634361424","21427251634360535","21427251634360534","21427251634360525","21427251634360524","21427251634360435","21427251634360434","21427251634360425","21427251634360424","21427251634271535","21427251634271534","21427251634271525","21427251634271524","21427251634271435","21427251634271434","21427251634271425","21427251634271424","21427251634270535","21427251634270534","21427251634270525","21427251634270524","21427251634270435","21427251634270434","21427251634270425","21427251634270424","21427251634261535","21427251634261534","21427251634261525","21427251634261524","21427251634261435","21427251634261434","21427251634261425","21427251634261424","21427251634260535","21427251634260534","21427251634260525","21427251634260524","21427251634260435","21427251634260434","21427251634260425","21427251634260424","21427251625371535","21427251625371534","21427251625371525","21427251625371524","21427251625371435"};
        octants[1]=new std::string[130] {"21427251635371526","21427251635371437","21427251635371436","21427251635371427","21427251635371426","21427251635370537","21427251635370536","21427251635370527","21427251635370526","21427251635370437","21427251635370436","21427251635370427","21427251635370426","21427251635361537","21427251635361536","21427251635361527","21427251635361526","21427251635361437","21427251635361436","21427251635361427","21427251635361426","21427251635360537","21427251635360536","21427251635360527","21427251635360526","21427251635360437","21427251635360436","21427251635360427","21427251635360426","21427251635271537","21427251635271536","21427251635271527","21427251635271526","21427251635271437","21427251635271436","21427251635271427","21427251635271426","21427251635270537","21427251635270536","21427251635270527","21427251635270526","21427251635270437","21427251635270436","21427251635270427","21427251635270426","21427251635261537","21427251635261536","21427251635261527","21427251635261526","21427251635261437","21427251635261436","21427251635261427","21427251635261426","21427251635260537","21427251635260536","21427251635260527","21427251635260526","21427251635260437","21427251635260436","21427251635260427","21427251635260426","21427251634371537","21427251634371536","21427251634371527","21427251634371526","21427251634371437","21427251634371436","21427251634371427","21427251634371426","21427251634370537","21427251634370536","21427251634370527","21427251634370526","21427251634370437","21427251634370436","21427251634370427","21427251634370426","21427251634361537","21427251634361536","21427251634361527","21427251634361526","21427251634361437","21427251634361436","21427251634361427","21427251634361426","21427251634360537","21427251634360536","21427251634360527","21427251634360526","21427251634360437","21427251634360436","21427251634360427","21427251634360426","21427251634271537","21427251634271536","21427251634271527","21427251634271526","21427251634271437","21427251634271436","21427251634271427","21427251634271426","21427251634270537","21427251634270536","21427251634270527","21427251634270526","21427251634270437","21427251634270436","21427251634270427","21427251634270426","21427251634261537","21427251634261536","21427251634261527","21427251634261526","21427251634261437","21427251634261436","21427251634261427","21427251634261426","21427251634260537","21427251634260536","21427251634260527","21427251634260526","21427251634260437","21427251634260436","21427251634260427","21427251634260426","21427251625371537","21427251625371536","21427251625371527","21427251625371526","21427251625371437"};
 (etc etc.)

.obj loader with glu, glut, gl etc. etc. together with sfml and thread loading .png files.
https://github.com/TheJavaProfessor/MINECRAFT-WORLD-CREATOR/tree/master/PACMAN_CUBERITE/src/viewer
(Integrated into big source project....but you can handle it)
If you download the whole thingie and set it up with codeblocks + seh compiler and some paths and dirs etc, you get cookie...) Its stuffed with usefull code from me and others. Operating check readme's and key handlers on how to use. If you like it i can give course. It has many features (no menu, only (all) keys), but combining features you can do lots of stuff, like endless canvas drawing plane for like sat. data downloaded (2d). (Now going to 3d...). Lots of threading stuff, minecraft 1.12.2 region file creator with multi command command blocks that build coral reefs while playing as demo. nbt readers/writers from/to disk/real ram, memory leak checkers to the byte/address (nbt allocating /deallocating stuff), game programming, shaders, blowing shaders (formula's) up to like 100x100 screens, google map data downloader, build in ffmpeg player, external ffmpeg input/output, sub pixel division for smooth recording, you name it...

Maybe the source could have some advantage. Like combining the endless (...) canvas with the 3d data .obj files, and/or render them on large size canvas for professional production of posters, 4k movies, or like 100x100 a4 poster sized billboards on 300+dpi. Lots of stuff you need a little course on it because it lacks a menu and/or documentation, but then hey, if you can program, you also can reverse engineer and read programs don't you? And i'm willing to help you out.
As said my goal for now (after playing with the 3d .obj loader/viewer) is to write a routing for voxelizing the 3d data from google, to make a nice minecraft level of some cities. The whole world could be an option, but then i need 100 pc's. Would be a nice thing seeing new york in mc.
(Didn't somebody do that already?). The minecraft region file creator then should create every 3d object and change it to your needs. See some demo's:

https://www.youtube.com/channel/UCEZXNkZ9KMqMUeuSRUv-BjA/playlists
https://www.youtube.com/user/gerardwensink/playlists
https://www.facebook.com/Minecraft-Worldeditor-110607880303634/
https://www.facebook.com/Pacman-Graphics-1601114056700700/
gerardwensink@gmail.com
https://www.facebook.com/gerard.wensink
What else can i say?
nothing for now.
O, wait.
Another thing i will make is drawing the .obj files onto the large canvas. Then you can combine (with like very large perspective angle (so far away objects are same size as in front)) the .obj files onto one big canvas. Then you can create posters like 500 x 500 screens or larger. Ending up with a downloaded and drawn 3d image of a whole city on like 1000000 pixels with/heigh. Just for showing off. Then i can render the zoomlevel 21 obj files large (much larger than the screen) onto the canvas, and combine like 100 x 100 .obj objects into one 2d plane. Maybe with some lightning/shadow opengl stuff for bling bling effect.
Bye. 
Please do not offend me, i'm just a simple tokkie programmer. But the source is (relative) stable for now. You can render movies over night for hours and hours at one piece.
Bye.
Have a nice life.

Sample of octants list generated: No doubles....

21427251635371524-21
21427251635371435-21
21427251635371434-21
21427251635371425-21
21427251635371424-21
21427251635370535-21
21427251635370534-21
21427251635370525-21
21427251635370524-21
21427251635370435-21
21427251635370434-21
21427251635370425-21
21427251635370424-21
21427251635361535-21
21427251635361534-21
21427251635361525-21
21427251635361524-21
21427251635361435-21
21427251635361434-21
21427251635361425-21
21427251635361424-21
21427251635360535-21
21427251635360534-21
21427251635360525-21
21427251635360524-21
21427251635360435-21
21427251635360434-21
....

**Comment by TheJavaProfessor** [comment]
Also speed up texture conversion with background threads (this case like 20):

`
#!/bin/bash

# converts all *.jpg and *.bmp files to *.png and patches model.mtl

dir="./downloaded_files/new/NewYork"
test $(find "$dir" -type d | head -n 1) || exit 1

# subdirectory (optional)
sub="$1"
if [ "$1" ]; then
  dir="$dir/$sub";
  test $(find "$dir" -type d | head -n 1) || exit 1
fi

function conv {
  mogrify -format png "$1" &&
  rm "$1"
}

if [[ -z $(find "$dir" -name '*.jpg' | head -n 1) ]]
then
  >&2 echo no \*.jpg in directory
fi

while read x
do
  >&2 echo "converting $x"
#  >&2 echo "converting $(basename "$x")"
  running=$(jobs -rp | wc -l)
  while [ $running -gt 20 ]
  do
	sleep 1
    running=$(jobs -rp | wc -l)
  done
  conv "$x" || exit 1 &
done < <(find "$dir" -name '*.jpg') &&

while read x
do
  >&2 echo "patching $x" &&
  >&2 echo "patching $(basename "$x")" &&
  sed -i.bak 's/.jpg/.png/' "$x" &&
  rm -f "$x.bak" &&
  if [ $? -ne 0 ]; then exit 1; fi
done < <(find "$dir" -name '*.mtl') &&

>&2 echo "done"


`

**Comment by psociety** [comment]
@TheJavaProfessor if i were you, i would place code under `` so markdown renders it properly. Example:
```c
std::string get_octant_NewYork(int &x, int &y) {
static std::string *octants[80];
static int first_do=1;
if (x<0 || y<0) {
x=80;y=58;
if (first_do==0) return "";
}
if (first_do==1) {
first_do=0;
x=42;y=130;
octants[0]=new std::string[130] {"21427251635371524","21427251635371435","21427251635371434","21427251635371425","21427251635371424","21427251635370535","21427251635370534","21427251635370525","21427251635370524","21427251635370435","21427251635370434","21427251635370425","21427251635370424","21427251635361535","21427251635361534","21427251635361525","21427251635361524","21427251635361435","21427251635361434","21427251635361425","21427251635361424","21427251635360535","21427251635360534","21427251635360525","21427251635360524","21427251635360435","21427251635360434","21427251635360425","21427251635360424","21427251635271535","21427251635271534","21427251635271525","21427251635271524","21427251635271435","21427251635271434","21427251635271425","21427251635271424","21427251635270535","21427251635270534","21427251635270525","21427251635270524","21427251635270435","21427251635270434","21427251635270425","21427251635270424","21427251635261535","21427251635261534","21427251635261525","21427251635261524","21427251635261435","21427251635261434","21427251635261425","21427251635261424","21427251635260535","21427251635260534","21427251635260525","21427251635260524","21427251635260435","21427251635260434","21427251635260425","21427251635260424","21427251634371535","21427251634371534","21427251634371525","21427251634371524","21427251634371435","21427251634371434","21427251634371425","21427251634371424","21427251634370535","21427251634370534","21427251634370525","21427251634370524","21427251634370435","21427251634370434","21427251634370425","21427251634370424","21427251634361535","21427251634361534","21427251634361525","21427251634361524","21427251634361435","21427251634361434","21427251634361425","21427251634361424","21427251634360535","21427251634360534","21427251634360525","21427251634360524","21427251634360435","21427251634360434","21427251634360425","21427251634360424","21427251634271535","21427251634271534","21427251634271525","21427251634271524","21427251634271435","21427251634271434","21427251634271425","21427251634271424","21427251634270535","21427251634270534","21427251634270525","21427251634270524","21427251634270435","21427251634270434","21427251634270425","21427251634270424","21427251634261535","21427251634261534","21427251634261525","21427251634261524","21427251634261435","21427251634261434","21427251634261425","21427251634261424","21427251634260535","21427251634260534","21427251634260525","21427251634260524","21427251634260435","21427251634260434","21427251634260425","21427251634260424","21427251625371535","21427251625371534","21427251625371525","21427251625371524","21427251625371435"};
octants[1]=new std::string[130] {"21427251635371526","21427251635371437","21427251635371436","21427251635371427","21427251635371426","21427251635370537","21427251635370536","21427251635370527","21427251635370526","21427251635370437","21427251635370436","21427251635370427","21427251635370426","21427251635361537","21427251635361536","21427251635361527","21427251635361526","21427251635361437","21427251635361436","21427251635361427","21427251635361426","21427251635360537","21427251635360536","21427251635360527","21427251635360526","21427251635360437","21427251635360436","21427251635360427","21427251635360426","21427251635271537","21427251635271536","21427251635271527","21427251635271526","21427251635271437","21427251635271436","21427251635271427","21427251635271426","21427251635270537","21427251635270536","21427251635270527","21427251635270526","21427251635270437","21427251635270436","21427251635270427","21427251635270426","21427251635261537","21427251635261536","21427251635261527","21427251635261526","21427251635261437","21427251635261436","21427251635261427","21427251635261426","21427251635260537","21427251635260536","21427251635260527","21427251635260526","21427251635260437","21427251635260436","21427251635260427","21427251635260426","21427251634371537","21427251634371536","21427251634371527","21427251634371526","21427251634371437","21427251634371436","21427251634371427","21427251634371426","21427251634370537","21427251634370536","21427251634370527","21427251634370526","21427251634370437","21427251634370436","21427251634370427","21427251634370426","21427251634361537","21427251634361536","21427251634361527","21427251634361526","21427251634361437","21427251634361436","21427251634361427","21427251634361426","21427251634360537","21427251634360536","21427251634360527","21427251634360526","21427251634360437","21427251634360436","21427251634360427","21427251634360426","21427251634271537","21427251634271536","21427251634271527","21427251634271526","21427251634271437","21427251634271436","21427251634271427","21427251634271426","21427251634270537","21427251634270536","21427251634270527","21427251634270526","21427251634270437","21427251634270436","21427251634270427","21427251634270426","21427251634261537","21427251634261536","21427251634261527","21427251634261526","21427251634261437","21427251634261436","21427251634261427","21427251634261426","21427251634260537","21427251634260536","21427251634260527","21427251634260526","21427251634260437","21427251634260436","21427251634260427","21427251634260426","21427251625371537","21427251625371536","21427251625371527","21427251625371526","21427251625371437"};
```

It makes your issue easier to read.

**Comment by retroplasma** [comment]
please merge this with your original issue (https://github.com/retroplasma/earth-reverse-engineering/issues/43)
