### ISSUE TITLE
How do you download a largely bounded rectangle area?

### ISSUE THREAD

**Issue by desmondCTNG** [retroplasma/earth-reverse-engineering#45]
I can download the a small area in 3d with the program, thank you for that. But I want to download a city, so I need to manually merge each piece of 3d area in blender. Is there a method to download large area? For example, typing left top corner coordinates, left bottom corner coordinates, right top corner coordinates and right bottom corner coordinates to form a large rectangle area to download.

**Comment by retroplasma** [comment]
You can specify North/South/West/East coordinates with LexSong's script from issue https://github.com/retroplasma/earth-reverse-engineering/issues/25 which gives you the octants inside that boundaries. Alternatively you can use a shorter octant string to download a larger area.

**Comment by desmondCTNG** [comment]
thank you, nice reply
