### ISSUE TITLE
Rotated Models

### ISSUE THREAD

**Issue by prrrszalony** [retroplasma/earth-reverse-engineering#49]
Hi,

All models are slightly rotated. Even model that model from readme have incorrect rotation. I don't know is this a bug or I'm doing something wrong.

![asd](https://i.imgur.com/gz4l3b8.jpg)

**Comment by retroplasma** [comment]
To normalize the rotation you can try LexSong's scripts from #30 instead of `center_scale_obj.js`.

Reason for rotation: `dump_obj.js` gives an obj at the original position on the globe. `center_scale_obj.js` puts it in the center and scales it, but it's still rotated.

**Comment by retroplasma** [comment]
`center_scale_obj.js` doesn't normalize the rotation. You can try LexSong's scripts from #30 instead.

**Comment by prrrszalony** [comment]
normalize_obj.py works like a charm! :) Thanks!
