### ISSUE TITLE
Request for a utility that resizes the octants to real world size

### ISSUE THREAD

**Issue by desmondCTNG** [retroplasma/earth-reverse-engineering#54]
May I request for a script that helps me to resize the object created, so that 1 meter or the object is equal to 1 meter of the real world. It is true that Blender has a resizing function, but sometimes the result is slightly inaccurate.

It will also be great if you can provide tips on how to make that script.

**Comment by bhaktatejas922** [comment]
+1 Could definitely use something like this too
