### ISSUE TITLE
Fix Model Popping.

### ISSUE THREAD

**Issue by 28lachie** [retroplasma/earth-reverse-engineering#56]
I have ran the python command and same thing happens with non textured meshes and in 3DS max, no clue how to fix it as I want to use this as a base to model from.
https://gfycat.com/AgonizingMeatyLeveret

**Comment by retroplasma** [comment]
You need to center/scale the model (see [blender tutorial](https://github.com/retroplasma/earth-reverse-engineering/blob/ca166786d618fe270450af9134116482c5963e48/exporter/BLENDER.md)). The values in the exported OBJ are too out there (world position) by default which makes 3d viewers pop like this.
