### ISSUE TITLE
Can't decode textures with rocktree.proto?

### ISSUE THREAD

**Issue by Heath123** [retroplasma/earth-reverse-engineering#58]
Hello! Sorry if this is the wrong place to ask, but I'm trying to implement this myself so I can get a better understanding of how the Google Earth protocol works and possibly implement it in other languages than C(++) and JS. When I import and use `exporter/lib/decode-resource.js` it works fine, but when I use `protoc` or [`protobufjs`](https://www.npmjs.com/package/protobufjs) with a DXT texture the data is too short and can't be decoded, and some data seems to be missing. Do you have any idea why? Thank you

**Comment by retroplasma** [comment]
Hi, the DXT is compressed using [CRN](https://github.com/BinomialLLC/crunch). It can be decompressed [like this](https://github.com/retroplasma/earth-reverse-engineering/blob/5f0add3a1ae663c7baa21c8d9d8350bc76141ee1/client/rocktree_ex.h#L116).

**Comment by Heath123** [comment]
Oh, thank you! I managed to decode and view the raw data using [crunch](https://github.com/BinomialLLC/crunch), so I can work from there and try using a library for it.
