### ISSUE TITLE
I can't show the download model in blender. Someone with the same problem?

### ISSUE THREAD

**Issue by CarlosFora** [retroplasma/earth-reverse-engineering#61]
I'm new with this. I download the model following the instructions, but when I import it on blender I can't show the model. Do I something wrong?
![imagen](https://user-images.githubusercontent.com/61824089/105819324-52a37f80-5fb8-11eb-885b-c0029db5e474.png)

**Comment by retroplasma** [comment]
Did you center it with `node center_scale_obj.js` and then opened `model.2.obj`? ([BLENDER.md](https://github.com/retroplasma/earth-reverse-engineering/blob/35af10d0e1a133dc217d63c59545a917f4e5fc3f/exporter/BLENDER.md)). Otherwise it would be somewhere off-screen.

**Comment by CarlosFora** [comment]
I think this is the problem. I will do it, thaks!!
