### ISSUE TITLE
Error: connect EACCES 142.250.184.110:443

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [retroplasma/earth-reverse-engineering#64]
Hello, i've tried with node.js v8 and v16 on windows 10, please help me identify the cause of this problem. I've tried with 2 different internet connections (proxy and no proxy).

npm config set proxy http://{url}:{port}
npm config set https-proxy http://{url}:{port}

command run: 
node lat_long_to_octant.js 37.420806884765625 -122.08419799804688

Gave up after 5 tries.
Error: connect EACCES 142.250.184.110:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -4092,
  code: 'EACCES',
  syscall: 'connect',
  address: '142.250.184.110',
  port: 443
}

**Comment by retroplasma** [comment]
Maybe some firewall? Does it work with something like `curl -i https://kh.google.com/rt/earth/PlanetoidMetadata` ?

**Comment by retroplasma** [comment]
Maybe some firewall? 
I don't know if you use WSL. Can you try this node script:
```javascript
require("https").get("https://example.com", r => console.log(r.statusCode)).on("error", console.error)
```

And these maybe: `curl https://example.com` or `openssl s_client -connect 142.250.184.110:443`

**Comment by huyutao3550346** [comment]
hi @retroplasma ,
I set the npm proxy like @GianniGi .
but return 
Error: connect ETIMEDOUT 172.217.160.110:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.160.110',
  port: 443
}
for me when I run node lat_long_to_octant.js 37.420806884765625 -122.08419799804688.
I use the require("https").get("https://example.com", r => console.log(r.statusCode)).on("error", console.error) 
return 200 for me.
