### ISSUE TITLE
Getting higher LOD for geometry and better textures

### ISSUE THREAD

**Issue by DmytroJDS** [retroplasma/earth-reverse-engineering#66]
Hi, can somebody explain how to get higher LOD for meshes and higher textures when using **dump_obj.js** if it possible.
Settings with max octant level 18 and dump obj level 20 provide for me those results: 

(also tried to play with different values which gave me same data)
Left - blender, Right - GEarth
<img width="1000" alt="compare" src="https://user-images.githubusercontent.com/18308591/123182597-76e88700-d498-11eb-9508-ae39a6dbcfcc.png">

This repo inspire me to write small experimental app which allows to easy download large chunks of 3d imagery. It uses **earth-reverse-engineering/exporter** code library as local web service to get octants and download obj files.
Some work in progress screens:
<img width="900" alt="tool" src="https://user-images.githubusercontent.com/18308591/123183954-579f2900-d49b-11eb-8038-107b20b67596.png">

**Comment by retroplasma** [comment]
Hi, try a higher max level. I put 30 and it went until 22:

```bash
node lat_long_to_octant.js 51.5002 -0.0213 # take result from 18
node dump_obj.js 216153517153737242 216153517153737246 216153517153737602 30 --parallel-search
node center_scale_obj.js
```

|level 22|level 20|
|--------|-------|
|<img src="https://user-images.githubusercontent.com/46618410/123523548-bccd6700-d6b3-11eb-9b3a-4a9da5ae4d3f.png">|<img src="https://user-images.githubusercontent.com/46618410/123523671-978d2880-d6b4-11eb-9aaf-cb36edcb1545.png">|

Nice looking app and KML feature!

**Comment by retroplasma** [comment]
Hi, try a higher max level. If you put 30 it goes until 22 in this city:

```bash
node lat_long_to_octant.js 51.5002 -0.0213 # take result from 18
node dump_obj.js 216153517153737242 216153517153737246 216153517153737602 30 --parallel-search
node center_scale_obj.js
```

|level 20|level 22|
|--------|-------|
|<img src="https://user-images.githubusercontent.com/46618410/123523671-978d2880-d6b4-11eb-9aaf-cb36edcb1545.png">|<img src="https://user-images.githubusercontent.com/46618410/123523548-bccd6700-d6b3-11eb-9b3a-4a9da5ae4d3f.png">|

Nice-looking app and KML feature!

**Comment by DmytroJDS** [comment]
@retroplasma Thanks a lot for helping! Higher levels works great! I'm also a figure out that blender ruin model geometry even on higher levels. This happened only if model wasn't centered. Probably it happens because of very long distance relatively to world center. Think i need to use other 3d editor for those stuff. :)

<img width="500" alt="Screenshot_4" src="https://user-images.githubusercontent.com/18308591/123702624-0a8ccf80-d86c-11eb-9422-f304c4fec845.png">
