### ISSUE TITLE
Maybe this might be helpfull

### ISSUE THREAD

**Issue by HakkaTjakka** [retroplasma/earth-reverse-engineering#69]
The repo https://github.com/HakkaTjakka/MinecraftWorldEditor is using this repo. Its adapted for bulk downloading and integration into a c++ program.
The project-obj has a nice Python script for converting lat / lon into the Build The Earth scale 1 to 1 projection, and there is a line of code (or 3) that calculates the height based on ellipsoid. You can convert your (adapted) script to .exe for convenience. It uses Python and the numpy and jnius lib. (projection.py). 
There are several options based on the number of parameters so you need to adapt for your own use like only output the height.
The proj-obj.py can be adapted for long lists of lat/lon to convert.
The original i have gotten is also on GitHub:
https://github.com/HakkaTjakka/project-obj
The minecraftworldeditor program also shows some nice conversions using lat/lon, on the 3d data, or projection into another (3d) space, opengl renderer, Wavefront .obj loader, conversion into .nbt compressed data that is loaded into gpu, texture loader with threads for speed. Msg if you need help on that. I've done conversions (also voxelizer) lots myself (with help of Google) lately. 
Just saying....

**Comment by retroplasma** [comment]
Links posted in other issues, closing
