### ISSUE TITLE
 [QUESTION] Caching

### ISSUE THREAD

**Issue by zrthstr** [retroplasma/earth-reverse-engineering#7]
It would be great to cache the downloaded map data.
 
@retroplasma  would you be interested in merging a PR with this feature if someone delivers?
What's the simplest and most robust way to add a map data caching mechanism?

**Comment by rastapasta** [comment]
hacky way would be replacing line [401 to 405](https://github.com/retroplasma/earth-reverse-engineering/blob/65a112e41139a7416b030989f47b424699e4beb5/index.js#L401-L405) with
```js
		let payload;
		try {
			payload = fs.readFileSync(url);
		} catch(e) {
			if (CACHE_ENABLED && cache[url]) {
				return cache[url];
			}
			payload = await fetchAsync(`${URL_PREFIX}${url}`);
			await fs.writeFileSync(url, payload);
		}
```

and doing a ```mkdir BulkMetadata NodeData``` before running the script.

happy codin' ;)

**Comment by retroplasma** [comment]
@zrthstr sure. dunno whats the best way. depends on what you want to do. if it makes sense and can be toggled via options, go ahead :)
