### ISSUE TITLE
Hang on end of node dump_obj.js?

### ISSUE THREAD

**Issue by HakkaTjakka** [retroplasma/earth-reverse-engineering#70]
I have an (adapted) dump_obj.js
It often (lately/suddenly) keeps hanging on exit. Is that a known thing?
https://github.com/HakkaTjakka/MinecraftWorldEditor/blob/master/EARTH/DUMP_OBJ_CITY.js

**Comment by retroplasma** [comment]
This is a modified version from another repository. If you can reproduce it with the one here feel free to reopen, with more details please.
