### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by KrishtaJ** [retroplasma/earth-reverse-engineering#8]
![image](https://user-images.githubusercontent.com/46688937/51137627-f9e76b00-1864-11e9-8461-c8d7a985efbe.png)

**Comment by catskul** [comment]
That issue title is not helpful. Can you please change it to  "Cannot find module 'sharp'"

Also, did you run `npm install` first?

**Comment by retroplasma** [comment]
`npm install`
